In [2]:
import numpy as np
lst = [1,2,3,4]
arr = np.array(lst)
arr

array([1, 2, 3, 4])

In [3]:
arr = np.arange(2, 11).reshape(3,3)
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [4]:
arr = np.zeros((1,10),dtype=int)
arr[0][5] = 11
arr

array([[ 0,  0,  0,  0,  0, 11,  0,  0,  0,  0]])

In [5]:
arr = np.arange(12,38)
arr

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [6]:
arr[::-1]

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

In [7]:
lst = [1,2,3,4]
arr = np.array(lst, dtype = float)
arr


array([1., 2., 3., 4.])

In [8]:
tuple = ([1,2,5] , [2,54,8])
arr = np.array(tuple)
arr

array([[ 1,  2,  5],
       [ 2, 54,  8]])

In [9]:
lst = [1,2,3,4]
lst2 = [10,20,30,40]
arr = np.append(lst,lst2)
arr


array([ 1,  2,  3,  4, 10, 20, 30, 40])

In [13]:
x = np.empty((3,4))
y = np.full((3,3),6)
y

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [21]:
import pandas as pd
ds = pd.Series([1,2,3,4])
ds

0    1
1    2
2    3
3    4
dtype: int64

In [23]:
ds = pd.Series([1,2,3,4])
lst = list(ds)
lst

[1, 2, 3, 4]

In [24]:
ds = pd.Series([1,2,3,4])
ds1 = pd.Series([23,42,2,33])
sub = ds + ds1 
sub

0    24
1    44
2     5
3    37
dtype: int64

In [25]:
ds = pd.Series([1,2,3,4])
ds1 = pd.Series([3,2,12,4])
check = ds1 == ds
check

0    False
1     True
2    False
3     True
dtype: bool

In [26]:
dic = {'ali' : 2 , 'sara' :21 , 'mohamad' : 233}
ds = pd.Series(dic)
ds

ali          2
sara        21
mohamad    233
dtype: int64

In [28]:
arr = np.array([2,31,42])
ds = pd.Series(arr)
arr
ds

0     2
1    31
2    42
dtype: int32

In [34]:
ds = pd.Series(['2','3','4','sas','sassasa'])
ds1 = pd.to_numeric(ds , errors='coerce') 
ds1

0    2.0
1    3.0
2    4.0
3    NaN
4    NaN
dtype: float64

In [38]:
d = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1,11]}
df = pd.DataFrame(data=d)
s1 = df.ix[:,0]

AttributeError: 'DataFrame' object has no attribute 'ix'

In [42]:
ds = pd.Series([1,2,3,4])
ds
arr = np.array(ds)
arr

array([1, 2, 3, 4], dtype=int64)

In [46]:
ds = pd.Series([12,22,332,1])
ds1 = pd.Series(ds).sort_values()
ds1

3      1
0     12
1     22
2    332
dtype: int64

In [50]:
ds = pd.Series([12,22,332,1])
ds1 = pd.Series([1,23,4,5])
ds2 = ds.append(ds1)
ds2


C:\Users\user\AppData\Local\Temp\ipykernel_10648\920904297.py:3: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ds2 = ds.append(ds1)


0     12
1     22
2    332
3      1
0      1
1     23
2      4
3      5
dtype: int64